version: 0.0
os: linux
files:
  - source: /
    destination: /www
hooks:
  AfterInstall:
    - location: /scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /scripts/start_server
      timeout: 180
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
